apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logging-ingress
  namespace: logging
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "logging-ip"
    networking.gke.io/managed-certificates: "logging-cert"
    networking.gke.io/v1beta1.FrontendConfig: "logging-frontend-config"
spec:
  rules:
  - host: grafana.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 80
  - host: loki.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loki
            port:
              number: 3100
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: logging-cert
  namespace: logging
spec:
  domains:
  - grafana.example.com
  - loki.example.com
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: logging-frontend-config
  namespace: logging
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
