apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-sa
  namespace: logging
  annotations:
    iam.gke.io/gcp-service-account: loki-sa@${PROJECT_ID}.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector-sa
  namespace: logging
  annotations:
    iam.gke.io/gcp-service-account: vector-sa@${PROJECT_ID}.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: loki-sa-workload-identity
  namespace: logging
spec:
  member: serviceAccount:${PROJECT_ID}.svc.id.goog[logging/loki-sa]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    external: loki-sa@${PROJECT_ID}.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: vector-sa-workload-identity
  namespace: logging
spec:
  member: serviceAccount:${PROJECT_ID}.svc.id.goog[logging/vector-sa]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    external: vector-sa@${PROJECT_ID}.iam.gserviceaccount.com
