apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 7.x.x
    chart: grafana
    helm:
      valueFiles:
      - $values/helm-values/grafana/values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
