apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 17.x.x
    chart: redis
    helm:
      valueFiles:
      - $values/helm-values/redis/values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
